App is working

diff --git a/devUtils/cordova_build_script b/devUtils/cordova_build_script
--- a/devUtils/cordova_build_script
+++ b/devUtils/cordova_build_script
@@ -1,5 +1,8 @@
 #!/bin/sh 
 
+##
+## Copyright 2014 Troy Weidman
+##
 
 # Set directory and project name
 TARGET="sorter"
@@ -41,15 +44,19 @@ cd ${TARGET}
 cordova platform add android
 cordova platform add ios
 
+# 
+# For now, do NOT do pre-build.  This may cause some config files to be incomplete.
+# 
 # Do preliminary build.  Check for any errors.
-cordova build >/dev/null 2>/dev/null
-if [ "$?" -eq 0 ]
-then
-	echo "Preliminary build successful"
-else
-	echo "Error: preliminary build not successful"
-	exit 1
-fi
+# cordova build >/dev/null 2>/dev/null
+# if [ "$?" -eq 0 ]
+# then
+# 	echo "Preliminary build successful"
+# else
+# 	echo "Error: preliminary build not successful"
+# 	exit 1
+# fi
+# 
 
 
 # Add the PlugIns
@@ -60,7 +67,11 @@ cordova plugin add org.apache.cordova.device
 cordova plugin add org.apache.cordova.dialogs
 cordova plugin add org.apache.cordova.console
 cordova plugin add org.apache.cordova.device-orientation
-cordova plugin add org.apache.cordova.splashscreen
+# cordova plugin add org.apache.cordova.splashscreen
+cordova plugin add org.apache.cordova.vibration
+cordova plugin add org.apache.cordova.file
+cordova plugin add org.apache.cordova.file-transfer
+
 
 
 echo ""
@@ -69,7 +80,7 @@ cordova plugin ls
 
 
 # Do final build.  Check for any errors.
-cordova build >/dev/null 2>/dev/null
+cordova build
 if [ "$?" -eq 0 ]
 then
 	echo "Final build successful"
@@ -81,8 +92,8 @@ fi
 # Set aside WWW for Reference
 mv www www_reference
 mkdir www
-cp www_reference/config.xml www
-
+cp    www_reference/config.xml www
+cp -R www_reference/res www
 
 
 #	Announce End of Script.
@@ -97,17 +108,7 @@ echo ""
 #
 #	Copy over icons
 #	Make sure icons display
-#	Copy over splash screens
-#	Make sure splash screens work
 #	
-#	Make sure apps are locked in Portrait (sensorPortrait for Android)
-#	Make sure apps are locked in Portrait (set iPhone and iPad for IOS)
-#	Add special Code to handle QA Server (self certification)
-#
-#	Make sure app stays running when HOME button is pressed (Android)
-#
-#	Add sure Credentials for Urban Airship added
-#	Make sure icons appear for UA Push Notification
 #
 #
 
